spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: jax
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

